name: Deploy to Production

on:
  workflow_run:
    workflows: ["CI/CD for Flask App"]
    types:
      - completed
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Stop any old Flask/gunicorn
        shell: powershell
        run: |
          Get-Process | Where-Object { $_.ProcessName -like "*python*" } | Stop-Process -Force -ErrorAction SilentlyContinue

      - name: Start app (temp)
        run: |
          cd /opt/flask-app
          nohup /opt/flask-app/venv/bin/gunicorn -w 2 -b 0.0.0.0:5000 app:app >/opt/flask-app/out.log 2>&1 &

