name: Deploy to Production

on:
  workflow_run:
    workflows: ["CI/CD for Flask App"]
    types:
      - completed
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: production-files
        path: ./deployment
        github-token: ${{ secrets.KEY }}
        run-id: ${{ github.event.workflow_run.id }}
    
    - name: Deploy to Server
      run: |
        echo "Deploying Flask application..."
        cd deployment
        echo "Deployment completed successfully!"
