name: CI/CD for Flask App

on:
  push:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build Project
      run: |
        echo "Building Flask application..."
        mkdir build
        cp app.py build/
        cp requirements.txt build/
    
    - name: Upload artifact to enable deployment
      uses: actions/upload-artifact@v3
      with:
        name: production-files
        path: ./build